// Firmware templates, ported verbatim from server/templates/*.jinja2 to nunjucks
// (Jinja2-compatible). Inlined as string constants so they bundle cleanly across
// tsc / vitest / esbuild with no loader config or runtime path resolution.

export const PLATFORMIO_INI = `; Generated by Sim Panel Manager — DO NOT EDIT MANUALLY
; Board: {{ board.name }} | Product: {{ board.identity.usbProduct }}
; Regenerate from the Sim Panel Manager app.

[env:{{ board.env_name }}]
platform = atmelavr
board = {{ board.env_name }}
framework = arduino
board_json_dir = boards

lib_deps =
    mheironimus/Joystick@^2.1.1

build_flags =
    -DUSB_VID={{ board.identity.usbVidHex }}
    -DUSB_PID={{ board.identity.usbPidHex }}
    -DUSB_PRODUCT="{{ board.identity.usbProduct }}"
    -DUSB_MANUFACTURER="Sim Panel Manager"

monitor_speed = 9600
`;

export const BOARD_JSON = `{
  "build": {
    "core": "arduino",
    "f_cpu": "16000000L",
    "hwids": [
      ["{{ board.identity.usbVidHex }}", "{{ board.identity.usbPidHex }}"]
    ],
    "mcu": "atmega32u4",
    "variant": "{{ board.build_variant }}",
    "usb_product": "{{ board.identity.usbProduct }}",
    "vid": "{{ board.identity.usbVidHex }}",
    "pid": "{{ board.identity.usbPidHex }}"
  },
  "frameworks": ["arduino"],
  "name": "{{ board.name }} (SPM Custom)",
  "upload": {
    "maximum_ram_size": 2560,
    "maximum_size": 28672,
    "protocol": "avr109",
    "require_upload_port": true,
    "use_1200bps_touch": true,
    "wait_for_upload_port": true,
    "speed": 57600
  },
  "url": "https://github.com/myclark/simpanman",
  "vendor": "Sim Panel Manager"
}
`;

export const MAIN_CPP = `// Generated by Sim Panel Manager — DO NOT EDIT MANUALLY
// Board:   {{ board.name }}
// Product: {{ board.identity.usbProduct }} (VID={{ board.identity.usbVidHex }} PID={{ board.identity.usbPidHex }})
// Regenerate from the Sim Panel Manager app.

#include <Arduino.h>
#include <Joystick.h>

// ── Joystick declaration ──────────────────────────────────────────────────────
Joystick_ Joystick(
    JOYSTICK_DEFAULT_REPORT_ID,
    JOYSTICK_TYPE_GAMEPAD,
    {{ total_buttons }},  // button count
    0,                    // hat switches
    {{ "true" if axis_flags.X else "false" }},        // X axis
    {{ "true" if axis_flags.Y else "false" }},        // Y axis
    {{ "true" if axis_flags.Z else "false" }},        // Z axis
    {{ "true" if axis_flags.Rx else "false" }},       // Rx axis
    {{ "true" if axis_flags.Ry else "false" }},       // Ry axis
    {{ "true" if axis_flags.Rz else "false" }},       // Rz axis
    {{ "true" if axis_flags.Slider2 else "false" }},  // Rudder  (Slider2)
    {{ "true" if axis_flags.Slider1 else "false" }},  // Throttle (Slider1)
    false,  // Accelerator
    false,  // Brake
    false   // Steering
);

{% if has_encoders %}
// ── Encoder state ─────────────────────────────────────────────────────────────
{% for enc in encoder_controls %}
volatile int enc_{{ enc.id | replace("-", "_") }}_count = 0;
{% if enc.mode == "axis" %}
int enc_{{ enc.id | replace("-", "_") }}_axis_val = {{ enc.axis_min }};
{% endif %}
{% endfor %}
{% endif %}

{% if button_controls or switch_controls %}
// ── Debounce state (previous values) ─────────────────────────────────────────
{% for ctl in button_controls %}
bool prev_btn_{{ ctl.id | replace("-", "_") }} = false;
{% endfor %}
{% for ctl in switch_controls %}
bool prev_sw_{{ ctl.id | replace("-", "_") }} = false;
{% endfor %}
{% endif %}

{% if interrupt_encoders %}
// ── Interrupt Service Routines for interrupt-capable encoders ─────────────────
{% for enc in interrupt_encoders %}
void isr_{{ enc.id | replace("-", "_") }}() {
    bool a = digitalRead({{ enc.pin_a_num }});
    bool b = digitalRead({{ enc.pin_b_num }});
    if (a != b) {
        enc_{{ enc.id | replace("-", "_") }}_count++;
    } else {
        enc_{{ enc.id | replace("-", "_") }}_count--;
    }
}
{% endfor %}
{% endif %}

// ── Setup ──────────────────────────────────────────────────────────────────────
void setup() {
{% for ctl in button_controls %}
    pinMode({{ ctl.pin_num }}, INPUT_PULLUP);
{% endfor %}
{% for ctl in switch_controls %}
    pinMode({{ ctl.pin_num }}, INPUT_PULLUP);
{% endfor %}
{% for sel in selector_controls %}
{% for pos in sel.positions %}
{% for pin in pos.pins %}
    pinMode({{ pin.pin_num }}, INPUT_PULLUP);
{% endfor %}
{% endfor %}
{% endfor %}
{% for enc in encoder_controls %}
    pinMode({{ enc.pin_a_num }}, INPUT_PULLUP);
    pinMode({{ enc.pin_b_num }}, INPUT_PULLUP);
{% endfor %}

{% for enc in interrupt_encoders %}
    attachInterrupt(
        digitalPinToInterrupt({{ enc.pin_a_num }}),
        isr_{{ enc.id | replace("-", "_") }},
        CHANGE
    );
{% endfor %}

    Joystick.begin(false);  // false = manual sendState each loop
}

// ── Loop ───────────────────────────────────────────────────────────────────────
void loop() {

    // ── Buttons ───────────────────────────────────────────────────────────────
{% for ctl in button_controls %}
    {
        bool active = (digitalRead({{ ctl.pin_num }}) == {% if ctl.inverted %}LOW{% else %}HIGH{% endif %});
        if (active != prev_btn_{{ ctl.id | replace("-", "_") }}) {
            prev_btn_{{ ctl.id | replace("-", "_") }} = active;
            Joystick.setButton({{ ctl.button_start }}, active ? 1 : 0);
        }
    }
{% endfor %}

    // ── Switches (SPDT: ON button + OFF button) ───────────────────────────────
{% for ctl in switch_controls %}
    {
        bool on = (digitalRead({{ ctl.pin_num }}) == {% if ctl.inverted %}LOW{% else %}HIGH{% endif %});
        if (on != prev_sw_{{ ctl.id | replace("-", "_") }}) {
            prev_sw_{{ ctl.id | replace("-", "_") }} = on;
            Joystick.setButton({{ ctl.button_on }}, on ? 1 : 0);
            Joystick.setButton({{ ctl.button_off }}, on ? 0 : 1);
        }
    }
{% endfor %}

    // ── Selectors ─────────────────────────────────────────────────────────────
{% for sel in selector_controls %}
{% for pos in sel.positions %}
    {
{% if pos.op == "single" %}
        bool active = (digitalRead({{ pos.pins[0].pin_num }}) == {% if pos.pins[0].inverted %}LOW{% else %}HIGH{% endif %});
{% elif pos.op == "and" %}
        bool active = true;
{% for pin in pos.pins %}
        active &= (digitalRead({{ pin.pin_num }}) == {% if pin.inverted %}LOW{% else %}HIGH{% endif %});
{% endfor %}
{% elif pos.op == "or" %}
        bool active = false;
{% for pin in pos.pins %}
        active |= (digitalRead({{ pin.pin_num }}) == {% if pin.inverted %}LOW{% else %}HIGH{% endif %});
{% endfor %}
{% endif %}
        Joystick.setButton({{ pos.button_idx }}, active ? 1 : 0);
    }
{% endfor %}
{% endfor %}

    // ── Polling encoders (non-interrupt pins) ─────────────────────────────────
{% for enc in polling_encoders %}
    {
        static uint8_t last_{{ enc.id | replace("-", "_") }} = 0;
        uint8_t a = digitalRead({{ enc.pin_a_num }});
        uint8_t b = digitalRead({{ enc.pin_b_num }});
        uint8_t state = (a << 1) | b;
        uint8_t prev = last_{{ enc.id | replace("-", "_") }};
        if (state != prev) {
            // Grey-code decode
            if (((prev ^ state) & 1) ^ ((state >> 1) & 1)) {
                enc_{{ enc.id | replace("-", "_") }}_count++;
            } else {
                enc_{{ enc.id | replace("-", "_") }}_count--;
            }
            last_{{ enc.id | replace("-", "_") }} = state;
        }
    }
{% endfor %}

    // ── Process encoder counts ────────────────────────────────────────────────
{% for enc in encoder_controls %}
{% set varname = "enc_" ~ enc.id | replace("-", "_") ~ "_count" %}
{% if enc.mode == "buttons" %}
    {
        int ticks = {{ varname }} / {{ enc.counts_per_detent }};
        {{ varname }} -= ticks * {{ enc.counts_per_detent }};
        if (ticks != 0) {
            int presses = (ticks > 0 ? ticks : -ticks) * {{ enc.presses_per_detent }};
            uint8_t btn = (ticks > 0) ? {{ enc.button_cw }} : {{ enc.button_ccw }};
            for (int i = 0; i < presses; i++) {
                Joystick.setButton(btn, 1);
                Joystick.sendState();
                delay({{ enc.pulse_ms }});
                Joystick.setButton(btn, 0);
                Joystick.sendState();
                if (i < presses - 1) delay({{ enc.pulse_ms }});
            }
        }
    }
{% elif enc.mode == "axis" %}
    {
        int ticks = {{ varname }} / {{ enc.counts_per_detent }};
        {{ varname }} -= ticks * {{ enc.counts_per_detent }};
        if (ticks != 0) {
{% set axvar = "enc_" ~ enc.id | replace("-", "_") ~ "_axis_val" %}
            {{ axvar }} += ticks * {{ enc.delta_per_step }};
{% if enc.wrap %}
            {
                int range = {{ enc.axis_max }} - {{ enc.axis_min }} + 1;
                while ({{ axvar }} < {{ enc.axis_min }}) {{ axvar }} += range;
                while ({{ axvar }} > {{ enc.axis_max }}) {{ axvar }} -= range;
            }
{% else %}
            if ({{ axvar }} < {{ enc.axis_min }}) {{ axvar }} = {{ enc.axis_min }};
            if ({{ axvar }} > {{ enc.axis_max }}) {{ axvar }} = {{ enc.axis_max }};
{% endif %}
            Joystick.{{ enc.axis_setter }}({{ axvar }});
        }
    }
{% endif %}
{% endfor %}

    // ── Analog inputs ─────────────────────────────────────────────────────────
{% for ctl in analog_controls %}
    {
{% if ctl.smoothing %}
        static float smooth_{{ ctl.id | replace("-", "_") }} = 0.0f;
        float raw_f = (float)analogRead({{ ctl.pin_num }});
        smooth_{{ ctl.id | replace("-", "_") }} =
            {{ ctl.smoothing }}f * raw_f +
            (1.0f - {{ ctl.smoothing }}f) * smooth_{{ ctl.id | replace("-", "_") }};
        int val = (int)smooth_{{ ctl.id | replace("-", "_") }};
{% else %}
        int val = analogRead({{ ctl.pin_num }});
{% endif %}
        val = map(val, {{ ctl.in_min }}, {{ ctl.in_max }}, {{ ctl.out_min }}, {{ ctl.out_max }});
{% if ctl.deadzone %}
        {
            int mid = ({{ ctl.out_min }} + {{ ctl.out_max }}) / 2;
            if (val > mid - {{ ctl.deadzone }} && val < mid + {{ ctl.deadzone }}) val = mid;
        }
{% endif %}
{% if ctl.invert %}
        val = {{ ctl.out_max }} + {{ ctl.out_min }} - val;
{% endif %}
        Joystick.{{ ctl.axis_setter }}(val);
    }
{% endfor %}

    Joystick.sendState();
    delay(1);
}
`;
